### ISSUE TITLE
compile error comeing from the missing header file for esp32 target (OCDOE-5)

### ISSUE THREAD

**Issue by mthii** [espressif/openocd-on-esp32#1]
missing header file: esp32/include/hal/deedic_gpio_cpu_ll.h for esp32

```
openocd-on-esp32/main/openocd/src/jtag/drivers/esp_gpio.c:19:10: fatal error: hal/dedic_gpio_cpu_ll.h: No such file or directory
   19 | #include <hal/dedic_gpio_cpu_ll.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems any other target headers are exists.

```
   $ find . -name dedic_gpio_cpu_ll.h
    ./esp32c3/include/hal/dedic_gpio_cpu_ll.h
    ./esp32c6/include/hal/dedic_gpio_cpu_ll.h
    ./esp32c2/include/hal/dedic_gpio_cpu_ll.h
    ./esp32s3/include/hal/dedic_gpio_cpu_ll.h
    ./esp32s2/include/hal/dedic_gpio_cpu_ll.h
    ./esp32h2/include/hal/dedic_gpio_cpu_ll.h
```

**Comment by erhankur** [comment]
@mthii An earlier version of this repo and submodule OpenOCD was supporting ESP32 using traditional GPIO access methods. We have switched to dedicated gpio APIs in order to speed up JTAG clock frequency. However, ESP32 doesn't support this feature. So, you can switch to the ESP32-S3 or try to look at the earlier commit and revert the changes. https://github.com/espressif/openocd-esp32/commit/535bc367b7c4ede97aad7ed29a0e0f4650ef9936

I will also update it to support both chips.

**Comment by erhankur** [comment]
@mthii are you waiting for ESP32 or could you manage to run it on ESP32-S3? I will prioritize according to your needs.

**Comment by mthii** [comment]
To be honest, I'm waiting for the both esp32 fix and esp32s3-devkit board delivery from cn. I tried to fix for the esp32 though, I gave up because of the too many difference between pretty old patches and current source without understanding in detail. I thought it was difficult for me then. But it seems it will be better to fix those caos.

**Comment by erhankur** [comment]
@mthii Due to the low memory footprint, supporting the ESP32 host will require more time and work. So we decided to drop ESP32 support. Readme and related files have been updated now. Please let us know if you have any issues with the ESP32-S3 host.

**Comment by mthii** [comment]
This seems hard work for the previous series chip. I would like to have just a simple debug probe as it was a little bit difficult even for the old jlink to debug. Do you know such a software debug probe for ESP32 series chips other than openocd on ESP32-S3 ?

**Comment by erhankur** [comment]
I think this will be the most comprehensive one in terms of supported target. Most of the debug probes work fine with arm targets but they don't have xtensa or riscv support. 

Can you tell me your difficulties in getting this run? So that we can try to address them.

As a debug probe, another option could be [esp_usb_bridge](https://github.com/espressif/esp-usb-bridge)
